packages:
  - templates/*
  - apps/*
  - packages/*

catalog:
  '@figma/ppg-dev-tools': ^1.1.0
  '@figma/ppg-eslint-config': ^1.1.0
  '@figma/ppg-tailwind-config': ^1.1.0
  '@figma/ppg-tsconfig': ^1.1.0
  '@figma/ppg-ui': ^1.1.0
  '@figma/ppg-vite-config': ^1.1.0
  motion: 12.34.5
  react-hook-form: 7.62.0
  zod: 3.25.58
