packages:
  - templates/*
  - apps/*
  - packages/*

catalog:
  '@figma/fpl-cli': 0.6.1
  '@figma/fpl-components': 0.6.0
  '@figma/fpl-icons': 0.6.0
  '@figma/fpl-tokens': 0.6.0
  '@figma/ppg-ai': ^1.10.0
  '@figma/ppg-dev-tools': ^1.10.0
  '@figma/ppg-eslint-config': ^1.10.0
  '@figma/ppg-tailwind-config': ^1.10.0
  '@figma/ppg-tsconfig': ^1.10.0
  '@figma/ppg-ui': ^1.10.0
  '@figma/ppg-vite-config': ^1.10.0
  '@figma/ppg-proto-cli': ^1.10.0
  '@figma/ppg-screenshot': ^1.10.0
  motion: 12.34.5
  react-hook-form: 7.62.0
  zod: 3.25.76
