import {
  DEFAULT_PAGE_BG,
  SceneGraph,
  createPaint,
  type SceneNode,
} from '@prototype/shared/canvas';

const DEMO_SCENE: Array<{ type: SceneNode['type']; props: Record<string, unknown> }> = [
  {
    type: 'STICKY_NOTE',
    props: {
      name: 'Sticky Note 1',
      x: -280,
      y: -120,
      width: 240,
      height: 240,
      rotation: 0,
      opacity: 1,
      cornerRadius: 0,
      fills: [createPaint({ type: 'SOLID', color: { r: 255, g: 226, b: 153 }, opacity: 1, visible: true })],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      effects: [{ type: 'DROP_SHADOW', visible: true }],
      characters: 'Welcome to FigJam!',
      fontFamily: 'Inter',
      fontSize: 24,
      fontWeight: 400,
      authorName: 'You',
      showAuthor: true,
    },
  },
  {
    type: 'STICKY_NOTE',
    props: {
      name: 'Sticky Note 2',
      x: 0,
      y: -140,
      width: 240,
      height: 240,
      rotation: 0,
      opacity: 1,
      cornerRadius: 0,
      fills: [createPaint({ type: 'SOLID', color: { r: 255, g: 184, b: 168 }, opacity: 1, visible: true })],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      effects: [{ type: 'DROP_SHADOW', visible: true }],
      characters: 'Add your ideas here',
      fontFamily: 'Inter',
      fontSize: 24,
      fontWeight: 400,
      authorName: 'You',
      showAuthor: true,
    },
  },
  {
    type: 'STICKY_NOTE',
    props: {
      name: 'Sticky Note 3',
      x: -140,
      y: 160,
      width: 240,
      height: 240,
      rotation: 0,
      opacity: 1,
      cornerRadius: 0,
      fills: [createPaint({ type: 'SOLID', color: { r: 179, g: 239, b: 189 }, opacity: 1, visible: true })],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      effects: [{ type: 'DROP_SHADOW', visible: true }],
      characters: 'Click to edit',
      fontFamily: 'Inter',
      fontSize: 24,
      fontWeight: 400,
      authorName: 'You',
      showAuthor: true,
    },
  },
  {
    type: 'ELLIPSE',
    props: {
      name: 'Circle 1',
      x: 200,
      y: -60,
      width: 100,
      height: 100,
      rotation: 0,
      opacity: 1,
      cornerRadius: 0,
      fills: [createPaint({ type: 'SOLID', color: { r: 196, g: 167, b: 255 }, opacity: 1, visible: true })],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      effects: [],
    },
  },
  {
    type: 'RECTANGLE',
    props: {
      name: 'Diamond 1',
      x: 220,
      y: 80,
      width: 80,
      height: 80,
      rotation: 45,
      opacity: 1,
      cornerRadius: 0,
      fills: [createPaint({ type: 'SOLID', color: { r: 147, g: 197, b: 253 }, opacity: 1, visible: true })],
      strokes: [],
      strokeWeight: 0,
      strokeAlign: 'CENTER',
      effects: [],
    },
  },
  {
    type: 'LINE',
    props: {
      name: 'Connector',
      x: 75,
      y: 55,
      width: 125,
      height: 0,
      rotation: -25,
      opacity: 1,
      strokes: [createPaint({ type: 'SOLID', color: { r: 100, g: 100, b: 100 }, opacity: 1, visible: true })],
      strokeWeight: 2,
      strokeAlign: 'CENTER',
      strokeDashPattern: [],
      startCap: 'NONE',
      endCap: 'NONE',
    },
  },
];

export function createInitialSceneGraph(): SceneGraph {
  const sg = new SceneGraph();
  const canvas = sg.createCanvas('Page 1', DEFAULT_PAGE_BG.color);

  for (const node of DEMO_SCENE) {
    sg.createNode(node.type, canvas.id, node.props);
  }

  return sg;
}
